export {default as  Home} from "./Home/Home"
export {default as About} from "./About/About"
export {default as Contact} from "./Contact/Contact"
export {default as Portfolio} from "./Portfolio/Portfolio"
export {default as Layout} from "./Layout/Layout"
export {default as Error} from "./Error/Error"
